export const textStyles = {
    display: {
        fontFamily: 'playfairDisplay',
        fontStyle: 'normal',
        fontWeight: 900,
        fontSize: '64px',
        lineHeight: '85px',
    },
    displaySmall: {
        fontFamily: 'playfairDisplay',
        fontStyle: 'normal',
        fontWeight: 900,
        fontSize: '36px',
        lineHeight: '44px',
    },
    h1: {
        fontFamily: 'montserrat',
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '42px',
        lineHeight: '51px',
    },
    h2: {
        fontFamily: 'montserrat',
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '36px',
        lineHeight: '44px',
    },
    h3: {
        fontFamily: 'montserrat',
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '26px',
        lineHeight: '32px',
    },
    h4: {
        fontFamily: 'montserrat',
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '22px',
        lineHeight: '27px',
    },
    h5: {
        fontFamily: 'montserrat',
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '16px',
        lineHeight: '20px',
    },
    body1: {
        fontFamily: 'montserrat',
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '16px',
        lineHeight: '20px',
    },
    // Should be defined on Figma as a variable.
    body1Bold: {
        fontFamily: 'montserrat',
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '16px',
        lineHeight: '20px',
    },
    body2: {
        fontFamily: 'montserrat',
        fontStyle: 'normal',
        fontWeight: 500,
        fontSize: '12px',
        lineHeight: '15px',
    },
    // Should be defined on Figma as a variable.
    body2Bold: {
        fontFamily: 'montserrat',
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '12px',
        lineHeight: '15px',
    },
    body3: {
        fontFamily: 'montserrat',
        fontStyle: 'normal',
        fontWeight: 500,
        fontSize: '10px',
        lineHeight: '12px',
    },
    // Should be defined on Figma as a variable.
    body3Bold: {
        fontFamily: 'montserrat',
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '10px',
        lineHeight: '12px',
    },
};
